title:       "Perwalian Akademik"
version:     "0005---04-Jul-2021"
copyright:   "2021-2021"
description: >- 
  This is a
  GitHub Page Template
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Rahmat M. Samik-Ibrahim"
address:          "Pamulang."
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://pa.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/UI-FASILKOM-OS/pa"
urlghpage:        "https://pa.vlsm.org/"
keywords:         "jekyll, testing"
github:           [metadata]

